# unstable_features = true
# force_multiline_blocks = true
# imports_layout = "HorizontalVertical"
# imports_granularity = "One"
# indent_style = "Visual"
# use_field_init_shorthand = true
# use_try_shorthand = true
# fn_single_line = true
# normalize_comments = true
# reorder_impl_items = true
# group_imports = "StdExternalCrate"
# struct_field_align_threshold = 30