[workspace]
members = [
    "kit",
    "ui",
    "icons",
    "common",
    "extensions",
    "native_extensions/emoji_selector",
]

[profile.rapid]
inherits = "dev"
opt-level = 2
incremental = true
overflow-checks = false
lto = "thin"
panic = "unwind"
codegen-units = 32

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[workspace.package]
version = "0.1.6"
rust-version = "1.70"

[workspace.dependencies]
dioxus = { version = "0.4" }
dioxus-hooks = { version = "0.4" }
dioxus-html = { version = "0.4" }
dioxus-router = { version = "0.4" }
dioxus-desktop = { version = "0.4", features = ["transparent"] }
raw-window-handle = "0.5"
dioxus-core = { version = "0.4" }
fermi = { version = "0.4" }
tokio-util = { version = "0.7", features = ["full"] }
arboard = "3.2"
humansize = "2.1.3"
uuid = { version = "1", features = ["serde", "v4"] }
libloading = "0.7.4"
warp = { git = "https://github.com/Satellite-im/Warp", rev = "7d1008e34ad02fd0725e45339c0e8c2af5608d1e" }
warp-ipfs = { git = "https://github.com/Satellite-im/Warp", rev = "7d1008e34ad02fd0725e45339c0e8c2af5608d1e" }
warp-blink-wrtc = { git = "https://github.com/Satellite-im/Warp", rev = "7d1008e34ad02fd0725e45339c0e8c2af5608d1e" }
rfd = "0.11.3"
mime = "0.3.16"
serde = "1.0"
serde_json = "1.0"
chrono = "0.4"
either = "1"
base64 = "0.20.0"
timeago = "0.4.0"
dirs = "4.0.0"
regex = "1.6.1"
opener = "0.5.0"
open = "3.2.0"
derive_more = "0.99"
colored = "2.0.0"
notify = "5.1.0"
rand = "0.8"
notify-rust = { version = "4.6.0", default-features = false, features = ["d"] }
titlecase = "2.2.1"

tempfile = "3.0.7"
fdlimit = "0.2"

once_cell = "1.17"

futures = "0.3"
tokio = { version = "1", features = ["full"] }
isolang = "2.2.0"
clap = { version = "4.1", features = ["derive"] }
fs_extra = "1.3"
walkdir = "2"
zip = "0.6.4"

image = "0.24"
linkify = "0.9.0"
reqwest = { version = "0.11", default-features=false, features = ["json", "rustls-tls", "stream"] }
select = "0.6.0"

common = { path = "common" }
extensions = { path = "extensions" }
kit = { path = "kit" }
icons = { path = "icons" }
