[workspace]
members = ["kit", "ui", "icons", "common", "extensions", "extension_example", "native_extensions/emoji_selector"]

[profile.rapid]
inherits = "dev"
opt-level = 2
incremental = true
overflow-checks = false
lto = "thin"
panic = "unwind"
codegen-units = 32

[profile.release.build-override]
opt-level = 3
codegen-units = 1