[package]
name = "emoji_selector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev="46cc07e04827f8ea63bd210eaf6b72727441b6bf" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus", rev = "46cc07e04827f8ea63bd210eaf6b72727441b6bf", features = [
    "transparent",
] }
extensions = { path = "../../extensions" }
common = { path = "../../common" }
kit = { path = "../../kit" }
emojis = "0.5.2"
once_cell = "1.17.1"