[package]
name = "icons"
rust-version = { workspace = true }
version = { workspace = true }
edition = "2021"

[dependencies]
dioxus = { workspace = true }
dioxus-html = { workspace = true }

[build-dependencies]
heck = "~0.4"
itertools = "~0.11"
scraper = "~0.17"
walkdir = "~2"

