[[people]]
blush = "😊"
smirk = "😏"
kissing_closed_eyes = "😚"
satisfied = "😆"
stuck_out_tongue_winking_eye = "😜"
kissing = "😗"
sleeping = "😴"
anguished = "😧"
confused = "😕"
unamused = "😒"
disappointed_relieved = "😥"
disappointed = "😞"
cold_sweat = "😰"
sob = "😭"
scream = "😱"
angry = "😠"
sleepy = "😪"
sunglasses = "😎"
smiling_imp = "😈"
innocent = "😇"
blue_heart = "💙"
green_heart = "💚"
heartpulse = "💗"
cupid = "💘"
star = "⭐"
boom = "💥"
exclamation = "❗"
grey_question = "❔"
sweat_drops = "💦"
fire = "🔥"
shit = "💩"
-1 = "👎"
punch = "👊"
v = "✌️"
raised_hand = "✋"
point_down = "👇"
raised_hands = "🙌"
clap = "👏"
fu = "🖕"
running = "🏃"
two_men_holding_hands = "👬"
dancers = "👯"
information_desk_person = "💁"
person_with_pouting_face = "🙎"
couplekiss = "💏"
haircut = "💇"
girl = "👧"
baby = "👶"
person_with_blond_hair = "👱"
construction_worker = "👷"
princess = "👸"
heart_eyes_cat = "😻"
scream_cat = "🙀"
pouting_cat = "😾"
see_no_evil = "🙈"
guardsman = "💂‍♂️"
lips = "👄"
ear = "👂"
tongue = "👅"
busts_in_silhouette = "👥"
smile = "😄"
smiley = "😃"
heart_eyes = "😍"
flushed = "😳"
grin = "😁"
stuck_out_tongue_closed_eyes = "😝"
kissing_smiling_eyes = "😙"
worried = "😟"
open_mouth = "😮"
hushed = "😯"
sweat_smile = "😅"
weary = "😩"
confounded = "😖"
persevere = "😣"
joy = "😂"
rage = "😡"
yum = "😋"
dizzy_face = "😵"
neutral_face = "😐"
alien = "👽"
purple_heart = "💜"
broken_heart = "💔"
two_hearts = "💕"
sparkling_heart = "💖"
star2 = "🌟"
collision = "💥"
question = "❓"
zzz = "💤"
notes = "🎶"
hankey = "💩"
plus_1 = "👍"
thumbsdown = "👎"
facepunch = "👊"
wave = "👋"
open_hands = "👐"
point_left = "👈"
pray = "🙏"
muscle = "💪"
walking = "🚶"
couple = "👫"
two_women_holding_hands = "👭"
ok_woman = "🙆‍♀️"
raising_hand = "🙋"
person_frowning = "🙍"
couple_with_heart = "💑"
nail_care = "💅"
woman = "👩"
older_woman = "👵"
man_with_gua_pi_mao = "👲"
cop = "👮"
smiley_cat = "😺"
kissing_cat = "😽"
crying_cat_face = "😿"
japanese_ogre = "👹"
hear_no_evil = "🙉"
skull = "💀"
kiss = "💋"
eyes = "👀"
love_letter = "💌"
speech_balloon = "💬"
laughing = "😆"
relaxed = "☺️"
kissing_heart = "😘"
relieved = "😌"
wink = "😉"
grinning = "😀"
stuck_out_tongue = "😛"
frowning = "😦"
grimacing = "😬"
expressionless = "😑"
sweat = "😓"
pensive = "😔"
fearful = "😨"
cry = "😢"
astonished = "😲"
tired_face = "😫"
triumph = "😤"
mask = "😷"
imp = "👿"
no_mouth = "😶"
yellow_heart = "💛"
heart = "❤️"
heartbeat = "💓"
revolving_hearts = "💞"
sparkles = "✨"
dizzy = "💫"
anger = "💢"
grey_exclamation = "❕"
dash = "💨"
musical_note = "🎵"
poop = "💩"
thumbsup = "👍"
ok_hand = "👌"
fist = "✊"
hand = "✋"
point_up = "☝️"
point_right = "👉"
point_up_2 = "👆"
metal = "🤘"
runner = "🏃"
family = "👪"
dancer = "💃"
no_good = "🙅"
bride_with_veil = "👰‍♀️"
bow = "🙇"
massage = "💆"
boy = "👦"
man = "👨"
older_man = "👴"
man_with_turban = "👳‍♂️"
angel = "👼"
smile_cat = "😸"
smirk_cat = "😼"
joy_cat = "😹"
japanese_goblin = "👺"
speak_no_evil = "🙊"
feet = "🐾"
droplet = "💧"
nose = "👃"
bust_in_silhouette = "👤"
thought_balloon = "💭"

[[nature]]
snowflake = "❄️"
cyclone = "🌀"
cat = "🐱"
hamster = "🐹"
frog = "🐸"
bear = "🐻"
cow = "🐮"
monkey = "🐒"
camel = "🐫"
panda_face = "🐼"
baby_chick = "🐤"
chicken = "🐔"
bug = "🐛"
beetle = "🪲"
tropical_fish = "🐠"
whale2 = "🐋"
ram = "🐏"
tiger2 = "🐅"
goat = "🐐"
pig2 = "🐖"
dragon_face = "🐲"
dromedary_camel = "🐪"
poodle = "🐩"
cherry_blossom = "🌸"
rose = "🌹"
maple_leaf = "🍁"
herb = "🌿"
palm_tree = "🌴"
chestnut = "🌰"
ear_of_rice = "🌾"
sun_with_face = "🌞"
new_moon = "🌑"
waxing_gibbous_moon = "🌔"
last_quarter_moon = "🌗"
first_quarter_moon_with_face = "🌛"
earth_americas = "🌎"
milky_way = "🌌"
umbrella = "☔"
snowman = "⛄"
foggy = "🌁"
dog = "🐶"
rabbit = "🐰"
tiger = "🐯"
pig = "🐷"
boar = "🐗"
horse = "🐴"
sheep = "🐑"
snake = "🐍"
hatched_chick = "🐥"
penguin = "🐧"
honeybee = "🐝"
snail = "🐌"
fish = "🐟"
dolphin = "🐬"
rat = "🐀"
rabbit2 = "🐇"
rooster = "🐓"
mouse2 = "🐁"
blowfish = "🐡"
leopard = "🐆"
paw_prints = "🐾"
tulip = "🌷"
sunflower = "🌻"
leaves = "🍃"
mushroom = "🍄"
evergreen_tree = "🌲"
seedling = "🌱"
shell = "🐚"
full_moon_with_face = "🌝"
waxing_crescent_moon = "🌒"
full_moon = "🌕"
waning_crescent_moon = "🌘"
moon = "🌔"
earth_asia = "🌏"
partly_sunny = "⛅"
cloud = "☁️"
zap = "⚡"
ocean = "🌊"
mouse = "🐭"
wolf = "🐺"
koala = "🐨"
pig_nose = "🐽"
monkey_face = "🐵"
racehorse = "🐎"
elephant = "🐘"
bird = "🐦"
hatching_chick = "🐣"
turtle = "🐢"
ant = "🐜"
octopus = "🐙"
whale = "🐳"
cow2 = "🐄"
water_buffalo = "🐃"
dragon = "🐉"
dog2 = "🐕"
ox = "🐂"
crocodile = "🐊"
cat2 = "🐈"
bouquet = "💐"
four_leaf_clover = "🍀"
hibiscus = "🌺"
fallen_leaf = "🍂"
cactus = "🌵"
deciduous_tree = "🌳"
blossom = "🌼"
globe_with_meridians = "🌐"
new_moon_with_face = "🌚"
first_quarter_moon = "🌓"
waning_gibbous_moon = "🌖"
last_quarter_moon_with_face = "🌜"
earth_africa = "🌍"
volcano = "🌋"

[[objects]]
bamboo = "🎍"
school_satchel = "🎒"
fireworks = "🎆"
rice_scene = "🎑"
santa = "🎅"
bell = "🔔"
tada = "🎉"
crystal_ball = "🔮"
floppy_disk = "💾"
movie_camera = "🎥"
iphone = "📱"
telephone_receiver = "📞"
minidisc = "💽"
speaker = "🔈"
mega = "📣"
alarm_clock = "⏰"
satellite = "📡"
mag_right = "🔎"
lock_with_ink_pen = "🔏"
bulb = "💡"
low_brightness = "🔅"
calling = "📲"
postbox = "📮"
shower = "🚿"
nut_and_bolt = "🔩"
moneybag = "💰"
pound = "💷"
money_with_wings = "💸"
outbox_tray = "📤"
postal_horn = "📯"
mailbox_with_no_mail = "📭"
bomb = "💣"
pill = "💊"
page_with_curl = "📃"
chart_with_upwards_trend = "📈"
clipboard = "📋"
card_index = "📇"
scissors = "✂️"
black_nib = "✒️"
triangular_ruler = "📐"
blue_book = "📘"
notebook_with_decorative_cover = "📔"
bookmark = "🔖"
telescope = "🔭"
basketball = "🏀"
tennis = "🎾"
bowling = "🎳"
bicyclist = "🚴"
swimmer = "🏊"
spades = "♠️"
diamonds = "♦️"
trophy = "🏆"
violin = "🎻"
black_joker = "🃏"
dart = "🎯"
memo = "📝"
art = "🎨"
trumpet = "🎺"
shoe = "👞"
lipstick = "💄"
tshirt = "👕"
dress = "👗"
kimono = "👘"
tophat = "🎩"
mans_shoe = "👞"
handbag = "👜"
eyeglasses = "👓"
tea = "🍵"
beer = "🍺"
tropical_drink = "🍹"
pizza = "🍕"
poultry_leg = "🍗"
curry = "🍛"
sushi = "🍣"
rice_cracker = "🍘"
stew = "🍲"
egg = "🥚"
custard = "🍮"
shaved_ice = "🍧"
cookie = "🍪"
lollipop = "🍭"
green_apple = "🍏"
cherries = "🍒"
strawberry = "🍓"
banana = "🍌"
sweet_potato = "🍠"
corn = "🌽"
gift_heart = "💝"
mortar_board = "🎓"
sparkler = "🎇"
jack_o_lantern = "🎃"
christmas_tree = "🎄"
no_bell = "🔕"
confetti_ball = "🎊"
cd = "💿"
camera = "📷"
computer = "💻"
phone = "☎️"
pager = "📟"
vhs = "📼"
mute = "🔇"
hourglass = "⌛"
watch = "⌚"
loop = "➿"
unlock = "🔓"
closed_lock_with_key = "🔐"
flashlight = "🔦"
electric_plug = "🔌"
email = "📧"
bath = "🛀"
toilet = "🚽"
hammer = "🔨"
yen = "💴"
euro = "💶"
e-mail = "📧"
envelope = "✉️"
mailbox_closed = "📪"
door = "🚪"
gun = "🔫"
syringe = "💉"
bookmark_tabs = "📑"
chart_with_downwards_trend = "📉"
calendar = "📆"
file_folder = "📁"
pushpin = "📌"
pencil2 = "✏️"
closed_book = "📕"
orange_book = "📙"
ledger = "📒"
name_badge = "📛"
newspaper = "📰"
soccer = "⚽"
8ball = "🎱"
golf = "⛳"
horse_racing = "🏇"
surfer = "🏄"
hearts = "♥️"
gem = "💎"
musical_score = "🎼"
space_invader = "👾"
flower_playing_cards = "🎴"
mahjong = "🀄"
pencil = "📝"
microphone = "🎤"
saxophone = "🎷"
sandal = "👡"
boot = "👢"
necktie = "👔"
running_shirt_with_sash = "🎽"
bikini = "👙"
crown = "👑"
closed_umbrella = "🌂"
pouch = "👝"
fishing_pole_and_fish = "🎣"
sake = "🍶"
beers = "🍻"
wine_glass = "🍷"
hamburger = "🍔"
meat_on_bone = "🍖"
fried_shrimp = "🍤"
fish_cake = "🍥"
rice = "🍚"
oden = "🍢"
bread = "🍞"
icecream = "🍦"
birthday = "🎂"
chocolate_bar = "🍫"
honey_pot = "🍯"
tangerine = "🍊"
grapes = "🍇"
peach = "🍑"
pear = "🍐"
eggplant = "🍆"
dolls = "🎎"
flags = "🎏"
wind_chime = "🎐"
ghost = "👻"
gift = "🎁"
tanabata_tree = "🎋"
balloon = "🎈"
dvd = "📀"
video_camera = "📹"
tv = "📺"
telephone = "☎️"
fax = "📠"
sound = "🔉"
loudspeaker = "📢"
hourglass_flowing_sand = "⏳"
radio = "📻"
mag = "🔍"
lock = "🔒"
key = "🔑"
high_brightness = "🔆"
battery = "🔋"
mailbox = "📫"
bathtub = "🛁"
wrench = "🔧"
seat = "💺"
dollar = "💵"
credit_card = "💳"
inbox_tray = "📥"
incoming_envelope = "📨"
mailbox_with_mail = "📬"
smoking = "🚬"
hocho = "🔪"
page_facing_up = "📄"
bar_chart = "📊"
scroll = "📜"
date = "📅"
open_file_folder = "📂"
paperclip = "📎"
straight_ruler = "📏"
green_book = "📗"
notebook = "📓"
books = "📚"
microscope = "🔬"
football = "🏈"
baseball = "⚾"
rugby_football = "🏉"
mountain_bicyclist = "🚵"
snowboarder = "🏂"
ski = "🎿"
clubs = "♣️"
ring = "💍"
musical_keyboard = "🎹"
video_game = "🎮"
game_die = "🎲"
clapper = "🎬"
book = "📖"
headphones = "🎧"
guitar = "🎸"
high_heel = "👠"
shirt = "👕"
womans_clothes = "👚"
jeans = "👖"
ribbon = "🎀"
womans_hat = "👒"
briefcase = "💼"
purse = "👛"
coffee = "☕"
baby_bottle = "🍼"
cocktail = "🍸"
fork_and_knife = "🍴"
fries = "🍟"
spaghetti = "🍝"
bento = "🍱"
rice_ball = "🍙"
ramen = "🍜"
dango = "🍡"
doughnut = "🍩"
ice_cream = "🍨"
cake = "🍰"
candy = "🍬"
apple = "🍎"
lemon = "🍋"
watermelon = "🍉"
melon = "🍈"
pineapple = "🍍"
tomato = "🍅"

[[places]]
house = "🏠"
office = "🏢"
bank = "🏦"
hotel = "🏨"
department_store = "🏬"
city_sunset = "🌆"
tent = "⛺"
japan = "🗾"
sunrise = "🌅"
bridge_at_night = "🌉"
ferris_wheel = "🎡"
ship = "🚢"
sailboat = "⛵"
rocket = "🚀"
steam_locomotive = "🚂"
bike = "🚲"
mountain_cableway = "🚠"
oncoming_automobile = "🚘"
taxi = "🚕"
bus = "🚌"
police_car = "🚓"
ambulance = "🚑"
train = "🚋"
bullettrain_front = "🚅"
monorail = "🚝"
ticket = "🎫"
traffic_light = "🚥"
beginner = "🔰"
busstop = "🚏"
checkered_flag = "🏁"
moyai = "🗿"
round_pushpin = "📍"
kr = "🇰🇷"
fr = "🇫🇷"
ru = "🇷🇺"
de = "🇩🇪"
house_with_garden = "🏡"
post_office = "🏣"
convenience_store = "🏪"
wedding = "💒"
european_post_office = "🏤"
japanese_castle = "🏯"
factory = "🏭"
mount_fuji = "🗻"
stars = "🌠"
carousel_horse = "🎠"
fountain = "⛲"
speedboat = "🚤"
rowboat = "🚣"
airplane = "✈️"
tram = "🚊"
aerial_tramway = "🚡"
tractor = "🚜"
car = "🚗"
oncoming_taxi = "🚖"
oncoming_bus = "🚍"
oncoming_police_car = "🚔"
minibus = "🚐"
station = "🚉"
bullettrain_side = "🚄"
railway_car = "🚃"
fuelpump = "⛽"
warning = "⚠️"
atm = "🏧"
barber = "💈"
crossed_flags = "🎌"
circus_tent = "🎪"
triangular_flag_on_post = "🚩"
cn = "🇨🇳"
es = "🇪🇸"
gb = "🇬🇧"
school = "🏫"
hospital = "🏥"
love_hotel = "🏩"
church = "⛪"
city_sunrise = "🌇"
european_castle = "🏰"
tokyo_tower = "🗼"
sunrise_over_mountains = "🌄"
statue_of_liberty = "🗽"
rainbow = "🌈"
roller_coaster = "🎢"
boat = "⛵"
anchor = "⚓"
helicopter = "🚁"
mountain_railway = "🚞"
suspension_railway = "🚟"
blue_car = "🚙"
red_car = "🚗"
articulated_lorry = "🚛"
rotating_light = "🚨"
fire_engine = "🚒"
truck = "🚚"
train2 = "🚆"
light_rail = "🚈"
trolleybus = "🚎"
vertical_traffic_light = "🚦"
construction = "🚧"
slot_machine = "🎰"
hotsprings = "♨️"
izakaya_lantern = "🏮"
performing_arts = "🎭"
jp = "🇯🇵"
us = "🇺🇸"
it = "🇮🇹"
uk = "🇬🇧"

[[symbols]]
one = "1️⃣"
four = "4️⃣"
seven = "7️⃣"
keycap_ten = "🔟"
hash = "#️⃣"
arrow_down = "⬇️"
capital_abcd = "🔠"
arrow_lower_left = "↙️"
arrow_up = "⬆️"
arrow_double_down = "⏬"
arrow_heading_down = "⤵️"
arrow_right_hook = "↪️"
arrow_up_small = "🔼"
rewind = "⏪"
ok = "🆗"
repeat_one = "🔂"
up = "🆙"
ng = "🆖"
signal_strength = "📶"
u55b6 = "🈺"
u6709 = "🈶"
u7533 = "🈸"
sa = "🈂️"
womens = "🚺"
parking = "🅿️"
baggage_claim = "🛄"
potable_water = "🚰"
congratulations = "㊗️"
left_luggage = "🛅"
cl = "🆑"
no_entry_sign = "🚫"
do_not_litter = "🚯"
no_pedestrians = "🚷"
eight_spoked_asterisk = "✳️"
vs = "🆚"
chart = "💹"
taurus = "♉"
leo = "♌"
scorpius = "♏"
aquarius = "♒"
six_pointed_star = "🔯"
b = "🅱️"
diamond_shape_with_a_dot_inside = "💠"
on = "🔛"
clock130 = "🕜"
clock11 = "🕚"
clock1230 = "🕧"
clock3 = "🕒"
clock430 = "🕟"
clock6 = "🕕"
clock730 = "🕢"
clock9 = "🕘"
copyright = "©️"
x = "❌"
interrobang = "⁉️"
heavy_plus_sign = "➕"
white_flower = "💮"
ballot_box_with_check = "☑️"
curly_loop = "➰"
trident = "🔱"
white_check_mark = "✅"
black_circle = "⚫"
large_blue_circle = "🔵"
small_blue_diamond = "🔹"
small_red_triangle_down = "🔻"
two = "2️⃣"
five = "5️⃣"
eight = "8️⃣"
1234 = "🔢"
block_symbols = "🔣"
arrow_forward = "▶️"
abcd = "🔡"
arrow_lower_right = "↘️"
arrow_upper_left = "↖️"
arrow_double_up = "⏫"
arrow_heading_up = "⤴️"
left_right_arrow = "↔️"
arrows_clockwise = "🔃"
fast_forward = "⏩"
twisted_rightwards_arrows = "🔀"
new = "🆕"
cool = "🆒"
cinema = "🎦"
u5272 = "🈹"
u6307 = "🈯"
u6e80 = "🈵"
u7a7a = "🈳"
restroom = "🚻"
baby_symbol = "🚼"
wheelchair = "♿"
accept = "🉑"
put_litter_in_its_place = "🚮"
m = "Ⓜ️"
customs = "🛃"
sos = "🆘"
underage = "🔞"
non-potable_water = "🚱"
children_crossing = "🚸"
eight_pointed_black_star = "✴️"
vibration_mode = "📳"
currency_exchange = "💱"
gemini = "♊"
virgo = "♍"
sagittarius = "♐"
pisces = "♓"
negative_squared_cross_mark = "❎"
ab = "🆎"
recycle = "♻️"
soon = "🔜"
clock10 = "🕙"
clock1130 = "🕦"
clock2 = "🕑"
clock330 = "🕞"
clock5 = "🕔"
clock630 = "🕡"
clock8 = "🕗"
clock930 = "🕤"
registered = "®️"
heavy_exclamation_mark = "❗"
o = "⭕"
heavy_minus_sign = "➖"
100 = "💯"
radio_button = "🔘"
wavy_dash = "〰️"
black_square = "black_square"
black_square_button = "🔲"
white_circle = "⚪"
large_blue_diamond = "🔷"
small_orange_diamond = "🔸"
three = "3️⃣"
six = "6️⃣"
nine = "9️⃣"
zero = "0️⃣"
arrow_backward = "◀️"
arrow_left = "⬅️"
abc = "🔤"
arrow_right = "➡️"
arrow_upper_right = "↗️"
arrow_down_small = "🔽"
leftwards_arrow_with_hook = "↩️"
arrow_up_down = "↕️"
arrows_counterclockwise = "🔄"
information_source = "ℹ️"
repeat = "🔁"
top = "🔝"
free = "🆓"
koko = "🈁"
u5408 = "🈴"
u6708 = "🈷️"
u7121 = "🈚"
u7981 = "🈲"
mens = "🚹"
no_smoking = "🚭"
metro = "🚇"
wc = "🚾"
secret = "㊙️"
passport_control = "🛂"
ideograph_advantage = "🉐"
id = "🆔"
no_mobile_phones = "📵"
no_bicycles = "🚳"
no_entry = "⛔"
heart_decoration = "💟"
mobile_phone_off = "📴"
aries = "♈"
cancer = "♋"
libra = "♎"
capricorn = "♑"
ophiuchus = "⛎"
a = "🅰️"
o2 = "🅾️"
end = "🔚"
clock1 = "🕐"
clock1030 = "🕥"
clock12 = "🕛"
clock230 = "🕝"
clock4 = "🕓"
clock530 = "🕠"
clock7 = "🕖"
clock830 = "🕣"
heavy_dollar_sign = "💲"
tm = "™️"
bangbang = "‼️"
heavy_multiplication_x = "✖️"
heavy_division_sign = "➗"
heavy_check_mark = "✔️"
link = "🔗"
part_alternation_mark = "〽️"
white_square = "white_square"
white_square_button = "🔳"
red_circle = "🔴"
large_orange_diamond = "🔶"
small_red_triangle = "🔺"