[package]
name = "common"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
bitflags = "2.4.2"
unic-langid = "0.9.4"
fluent-templates = "0.9.1"
notify = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
clap = { workspace = true }
rodio = "0.17.3"
uuid = { workspace = true }
notify-rust = { workspace = true }
dirs = { workspace = true }
base64 = { workspace = true }
lipsum = "0.9.0"
chrono = { workspace = true }
rand = { workspace = true }
image = { workspace = true }
names = "0.14.0"
titlecase = { workspace = true }
substring = "1.4.5"
plot_icon = "0.3.0"
tracing.workspace = true
parking_lot.workspace = true
icons = { workspace = true }
humansize = { workspace = true }
zip = "0.6.6"
walkdir = { workspace = true }
extensions = { workspace = true }
regex = { workspace = true }

futures = { workspace = true }
tokio = { workspace = true }

tempfile = { workspace = true }

warp = { workspace = true }
warp-ipfs = { workspace = true }
warp-blink-wrtc = { workspace = true }


dioxus = { workspace = true }
dioxus-desktop = { workspace = true, features = ["transparent"] }
dioxus-signals = { workspace = true }
derive_more = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25.0"
objc = "0.2.7"
core-foundation = "0.9.4"
mac-notification-sys = "0.6.1"

[target.'cfg(target_env = "msvc")'.dependencies.windows]
version = "0.54.0"
features = [
    "Win32_Foundation",
    "Foundation_Collections",
    "Win32_System_SystemInformation",
    "Data_Xml_Dom",
    "UI_Notifications",
]

[target.'cfg(target_env = "gnu")'.dependencies.windows]
version = "0.54.0"
features = [
    "Win32_Foundation",
    "Foundation_Collections",
    "Win32_System_SystemInformation",
    "Win32_System_LibraryLoader",
    "Data_Xml_Dom",
    "UI_Notifications",
]

[features]
production_mode = []
