name: Build Linux in PR

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  check:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Get latest package list
        run: sudo apt-get update
      - name: Install libwebkit2gtk
        run: sudo apt-get install -y build-essential pkg-config libssl-dev libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev librust-alsa-sys-dev dpkg-dev gzip libxdo-dev
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build executable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.70.0
          override: true
      - run: cargo build
