# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: [pull_request]

name: Cargo Workflow

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    name: Cargo Checks
    runs-on: ubuntu-latest
    steps:
      - name: Get new package info
        run: sudo apt-get update
      - name: Install libwebkit2gtk
        run: sudo apt-get install -y build-essential pkg-config libssl-dev libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev librust-alsa-sys-dev libxdo-dev --fix-missing
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run cargo checks
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.73.0
          components: rustfmt, clippy
      - run: cargo clippy --no-deps -- -D warnings
      - run: cargo fmt --check

      - name: Add linter failing label if cargo workflow fails
        if: failure()
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            linter failing
          type: add

      - name: Remove label if all test jobs succeeded
        if: success()
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            linter failing
          type: remove
