name: Remove All Labels

on:
  pull_request:
    types: [closed]

jobs:
  remove_labels:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: rogerluan/label-remover@v1.1.0
        with:
          github_token: ${{ secrets.github_token }}
